name: Build docker image
on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:

  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Install cosign
      if: github.event_name != 'pull_request'
      uses: sigstore/cosign-installer@v2.8.1
      with:
        cosign-release: 'v1.13.1'
    - name: Extract Docker metadata
      uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
      with:
        images: ghcr.io/justsem/${{ env.IMAGE_NAME }}
    - uses: docker/login-action@v2.1.0
      name: Login to GHCR
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build API image
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        file: Dockerfile
        tags: |
          ghcr.io/justsem/cs-openresty-bouncer:latest
          ghcr.io/justsem/cs-openresty-bouncer:${{ github.sha }}
          ghcr.io/justsem/cs-openresty-bouncer:${{ github.ref_name }}
    - name: Sign the published Docker image
      if: ${{ github.event_name != 'pull_request' }}
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}
